version: '2'
services:
  web: 
    image: httpd
    ports: 
    -  "80:80"
  db:
    image: mysql
    environment: 
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_DATABASE=mydb
    ports:
    - "3306:3306"
